[workspace]
members = [
    "programs/*",
    "tests/hosted",
    "tests/mock-adapter",
    "tests/bench-program",
    "libraries/rust/*",
    "libraries/ts/bonds/wasm-utils",
    "tools/*"
]

[patch.crates-io]
jet-proto-math = { git = "https://github.com/jet-lab/program-libraries", branch = "main" }
