[package]
name = "jet-test-service"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "jet_test_service"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
testing = []

[dependencies]
anchor-lang = "0.26"
anchor-spl = "0.26"

pyth-sdk-solana = "0.7"
bytemuck = "1.7"

spl-token-swap = { version = "2.1", features = ["no-entrypoint"] }
jet-program-common = { path = "../../libraries/rust/program-common" }
jet-margin = { path = "../margin", features = ["cpi", "no-entrypoint"] }
orca-whirlpool = { package = "whirlpool", git = "https://github.com/jet-lab/whirlpools", branch = "update-anchor-25", features = ["cpi", "no-entrypoint"] }