name: TS Lib Publish

on:
  push:
    branches: 
      - "master"
    paths:
      - "libraries/ts/margin/src/**"
  workflow_dispatch: {}

jobs:
    runs-on: ubuntu-latest

    publish:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup Nodejs
          uses: actions/checkout@v2
          with:
            cache: npm

        - name: Install Dependencies
          run: npm ci

        - name: Semantic Release
          run: npm run semantic-release
          env: 
            NPM_TOKEN: ${{secrets.NPM_TOKEN}}
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}